"""Offline DOM integration tests. No installed-extension or live-API claim.
Requires Python + Playwright, with BROWSER_PATH pointing to Chromium/Chrome.
Run: python tests/browser_smoke.py
"""
import os, re, json
from urllib.parse import urlsplit, unquote
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'qa-results'; OUT.mkdir(exist_ok=True)
SHOTS = ROOT / 'docs' / 'screenshots'; SHOTS.mkdir(parents=True, exist_ok=True)
A, B, C = 'a'*40, 'b'*40, 'c'*40
checks=[]; errors=[]
def fulfill_asset(route):
    # Actual packaged bytes, supplied locally because this harness is offline.
    name = unquote(urlsplit(route.request.url).path.removeprefix('/dist/'))
    path = (ROOT/'dist'/name).resolve()
    if not path.is_relative_to((ROOT/'dist').resolve()) or not path.is_file():
        route.fulfill(status=404, body='Missing fixture asset'); return
    mime = {'.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon'}.get(path.suffix,'application/octet-stream')
    route.fulfill(status=200,content_type=mime,body=path.read_bytes(),headers={'Access-Control-Allow-Origin':'*'})
def logo_ok(page, selector, size, name):
    logo=page.locator(selector);logo.wait_for()
    logo.evaluate('(e)=>e.decode()')
    ok(logo.evaluate('(e)=>e.complete && e.naturalWidth===412 && e.naturalHeight===412'),name+' decodes the new SVG')
    ok(logo.evaluate('(e)=>e.getBoundingClientRect().width')==size,name+' has the correct displayed size')
def ok(condition, name):
    if not condition: raise AssertionError(name)
    checks.append(name); print('PASS:',name,flush=True)
def boot(page, mode='repo'):
    page.on('pageerror', lambda err: errors.append(str(err)))
    page.set_content((ROOT/'qa/fixture.html').read_text() if mode=='repo' else '<html><head></head><body><main id="app"></main></body></html>')
    page.evaluate('(mode)=>globalThis.__RD_QA_MODE=mode', mode)
    files=['src/shared/core.js','src/shared/i18n.js','src/shared/ui.js','src/background/store.js','src/background/github.js','src/background/service.js','qa/harness.js']
    if mode=='repo': files+=['src/content/styles.js','src/content/panel.js','src/content/index.js']
    for f in files: page.add_script_tag(content=(ROOT/f).read_text())
    page.evaluate('QA.ready()')
    if mode!='repo':
        page.add_style_tag(content=(ROOT/'src/options/styles.css').read_text())
        if mode=='popup': page.add_style_tag(content=(ROOT/'src/popup/styles.css').read_text().replace("@import url('../options/styles.css');",''))
        page.add_script_tag(content=(ROOT/f'src/{mode}/index.js').read_text())
def refresh(page, **state):
    page.evaluate('(s)=>QA.set(s)',state)
    page.get_by_role('button',name='Refresh',exact=True).click()
    page.wait_for_function("!document.querySelector('#repodelta-panel-host').shadowRoot.querySelector('[aria-busy=true]')")
with sync_playwright() as p:
    executable=os.environ.get('BROWSER_PATH','/usr/bin/chromium')
    browser=p.chromium.launch(executable_path=executable,headless=True,args=['--no-sandbox'])
    context=browser.new_context(viewport={'width':1365,'height':900})
    context.route('http://127.0.0.1:5198/dist/**',fulfill_asset)
    page=context.new_page();boot(page)
    toolbar=page.locator('#repodelta-button-host button');toolbar.wait_for()
    ok(page.locator('#repodelta-button-host').count()==1,'One header badge is injected')
    logo_ok(page,'.rd-badge-logo',16,'Header badge logo')
    ok(page.evaluate('QA.calls.length')==0,'Untracked visit makes zero API calls')
    toolbar.click();page.get_by_role('heading',name='Your next visit starts here.').wait_for()
    ok(page.evaluate('async()=>Object.keys(await QA.store.checkpoints()).length')==0,'Opening panel does not create a checkpoint')
    page.get_by_role('button',name='Start tracking here',exact=True).click();page.get_by_role('heading',name='You are caught up to this revision.').wait_for()
    ok(page.evaluate("async()=>(await QA.store.checkpoints())['octo/demo'].sha")==A,'First explicit checkpoint saves the displayed SHA')
    refresh(page,head=B)
    page.get_by_role('heading',name='3 commits since your checkpoint').wait_for()
    ok(page.locator('.rd-file').count()==7,'Seven file changes render with status and line counts')
    logo_ok(page,'.rd-logo',28,'Panel logo')
    logo_ok(page,'.rd-badge-logo',16,'Header badge after a state update')
    page.screenshot(path=str(SHOTS/'01-files-en.png'))
    search=page.get_by_role('searchbox',name='Filter file paths');search.fill('src/types.js')
    ok(page.locator('.rd-file').count()==1,'Path filter matches previous filename of a rename')
    search.fill('');page.get_by_role('combobox',name='File change type').select_option('removed')
    ok(A in page.locator('.rd-file a').get_attribute('href'),'Deleted file link is pinned to the saved checkpoint')
    page.get_by_role('combobox',name='File change type').select_option('all')
    page.get_by_role('tab',name=re.compile('Commits')).click()
    ok(page.locator('.rd-commit').count()==3,'Commit tab shows chronological commit rows')
    page.get_by_role('tab',name=re.compile('Commits')).press('ArrowLeft')
    ok(page.get_by_role('tab',name=re.compile('Files')).get_attribute('aria-selected')=='true','Arrow keys change accessible tabs')
    page.get_by_role('button',name='Interface language').click();page.get_by_role('heading',name='마지막 확인 이후 커밋 3개').wait_for()
    ok(page.evaluate("async()=>(await QA.store.settings()).language")=='ko','KR toggle saves a language preference')
    page.evaluate('QA.dark()')
    ok(page.locator('.rd-dialog').evaluate("e=>getComputedStyle(e).backgroundColor")=='rgb(13, 17, 23)','In-page dialog inherits dark GitHub theme tokens')
    page.screenshot(path=str(SHOTS/'02-files-ko-dark.png'))
    page.set_viewport_size({'width':390,'height':844})
    ok(page.locator('.rd-dialog').evaluate('e=>e.scrollWidth<=e.clientWidth+2'),'Dialog has no horizontal overflow at 390px')
    page.screenshot(path=str(SHOTS/'03-compact-ko.png'))
    page.set_viewport_size({'width':1365,'height':900});page.evaluate('QA.dark(false)')
    page.get_by_role('button',name='화면 언어').click();page.get_by_role('heading',name='3 commits since your checkpoint').wait_for()
    page.evaluate("QA.set({head:'c'.repeat(40)})")
    page.get_by_role('button',name='Mark this revision reviewed',exact=True).click()
    ok(page.get_by_text(re.compile('Acknowledge bbbbbbb')).is_visible(),'Confirmation names the exact viewed revision')
    page.get_by_role('button',name='Confirm',exact=True).click();page.get_by_role('heading',name='You are caught up to this revision.').wait_for()
    ok(page.evaluate("async()=>(await QA.store.checkpoints())['octo/demo'].sha")==B,'A new upstream HEAD is not silently included in acknowledgment')
    page.keyboard.press('Escape')
    ok(page.locator('#repodelta-panel-host').count()==0,'Escape closes the native dialog')
    ok(toolbar.evaluate('e=>e.getRootNode().activeElement===e'),'Focus returns to the header badge')
    toolbar.click();page.get_by_role('button',name='Refresh',exact=True).wait_for()
    page.evaluate('QA.seed()');refresh(page,head=B,total=102,fileCount=7)
    page.get_by_role('tab',name=re.compile('Commits')).click()
    ok(page.locator('.rd-commit').count()==100,'Only the first 100 commits load initially')
    page.get_by_role('button',name='Load more commits',exact=True).click()
    page.wait_for_function("document.querySelector('#repodelta-panel-host').shadowRoot.querySelectorAll('.rd-commit').length===102")
    ok(page.locator('.rd-commit').count()==102,'Next commit page loads on demand')
    page.get_by_role('tab',name=re.compile('Files')).click()
    ok(page.locator('.rd-file').count()==7,'First-page file changes survive commit pagination')
    refresh(page,fileCount=300,total=3)
    ok(page.get_by_text(re.compile('GitHub returned 300 files')).is_visible(),'300-file result is labeled possibly incomplete')
    refresh(page,fileCount=7,xss=True)
    ok(page.locator('.rd-file img').count()==0 and page.locator('.rd-file a').first.inner_text().startswith('<img'),'Untrusted filename is rendered as text, not HTML')
    refresh(page,xss=False,branch='release/next')
    page.get_by_role('heading',name='The default branch changed.').wait_for()
    page.get_by_role('button',name='Reset to this revision',exact=True).click();page.get_by_role('button',name='Cancel',exact=True).click()
    ok(page.evaluate("async()=>(await QA.store.checkpoints())['octo/demo'].branch")=='main','Canceling branch reset preserves the original checkpoint')
    refresh(page,branch='main',relation='diverged')
    ok(page.get_by_role('heading',name='The commit history changed.').is_visible(),'Rewritten history is not displayed as an ordinary update')
    refresh(page,relation='ahead',repoId=999)
    ok(page.get_by_role('heading',name='This repository has a different identity.').is_visible(),'Repository ID replacement receives a distinct warning')
    refresh(page,repoId=42,compareError=404)
    ok(page.get_by_role('heading',name='The saved comparison is unavailable.').is_visible(),'Unavailable comparison receives an uncertainty-preserving warning')
    refresh(page,compareError=0,error=429)
    ok(page.get_by_role('alert').filter(has_text='rate limit').is_visible(),'API rate limit is displayed without hiding the error')
    n=page.evaluate('QA.calls.length');page.wait_for_timeout(250)
    ok(page.evaluate('QA.calls.length')==n,'Rate-limited view does not automatically retry')
    page.keyboard.press('Escape');page.evaluate('QA.set({error:0})');n=page.evaluate('QA.calls.length');page.evaluate("QA.navigate('octo','another')")
    page.wait_for_timeout(250)
    ok(page.locator('#repodelta-button-host').count()==1 and page.locator('#repodelta-panel-host').count()==0,'Simulated repository navigation leaves one badge and no stale panel')
    ok(page.evaluate('QA.calls.length')==n,'Navigating to an untracked repository makes no API call')
    page.evaluate("document.querySelector('ul.pagehead-actions').remove()")
    page.wait_for_timeout(250)
    ok(page.locator('#repodelta-button-host').count()==1,'Missing header falls back to a single floating control')
    options=context.new_page();boot(options,'options')
    options.get_by_role('heading',name='Your GitHub reading checkpoints.').wait_for()
    logo_ok(options,'.brand-logo',32,'Settings logo')
    options.get_by_label('GitHub personal access token',exact=True).fill('github_pat_'+'x'*30)
    options.get_by_role('button',name='Use for this session',exact=True).click()
    options.get_by_text('Session token saved. Cached API data was cleared.').wait_for()
    ok(options.get_by_label('GitHub personal access token',exact=True).input_value()=='','Token input is cleared after saving')
    ok('github_pat_' not in options.evaluate('async()=>JSON.stringify(await chrome.storage.local.get(null))'),'Token is absent from simulated local storage')
    options.evaluate('QA.seed()')
    # Refresh the actual options script against the same simulated extension state.
    options.add_script_tag(content=(ROOT/'src/options/index.js').read_text())
    options.get_by_role('link',name='octo/demo',exact=True).wait_for()
    options.get_by_role('combobox',name='Interface language').select_option('ko')
    options.get_by_role('heading',name='GitHub 읽기 기록의 기준점.').wait_for()
    options.screenshot(path=str(SHOTS/'04-options-ko.png'),full_page=True)
    ok(options.get_by_role('link',name='octo/demo',exact=True).is_visible(),'Checkpoint manager renders saved repository entries')
    backup=options.evaluate("async()=>(await RepoDelta.rpc({type:'EXPORT'})).text")
    ok('github_pat_' not in backup and 'revision' not in backup,'UI export path excludes token and internal revision data')
    options.get_by_role('button',name='모든 기준점 삭제',exact=True).click();options.get_by_role('button',name='취소',exact=True).click()
    ok(options.evaluate('async()=>Object.keys(await QA.store.checkpoints()).length')==1,'Canceling delete-all leaves saved checkpoints intact')
    popup=context.new_page();popup.set_viewport_size({'width':350,'height':390});boot(popup,'popup')
    logo_ok(popup,'.brand-logo',32,'Popup logo')
    popup.locator('body').screenshot(path=str(SHOTS/'05-popup-en.png'))
    ok(not errors,'No uncaught JavaScript errors during offline DOM regression')
    report={'mode':'Offline Chromium DOM harness; simulated Chrome APIs, GitHub responses, persistence and navigation','browser':browser.version,'passed':len(checks),'checks':checks,'pageErrors':errors,'notVerified':['Native MV3 installation and service-worker lifecycle','Live GitHub layout and API authentication','Native extension session persistence across browser restart','Actual Chrome Web Store review','Real browser download completion']}
    (OUT/'browser-results.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
    print(json.dumps({'passed':len(checks),'browser':browser.version,'pageErrors':errors},ensure_ascii=False),flush=True)
    context.close();browser.close()
