import test from 'node:test';
import assert from 'node:assert/strict';
import {R,A,B,C,ref,meta,cp,apiRepo,apiDiff,apiCommit} from './helpers.mjs';
for(const url of ['https://github.com/octo/demo','https://github.com/octo/demo/tree/feature/foo','https://github.com/octo/demo/issues/42','https://github.com/octo/demo.git'])test(`parse repository: ${url}`,()=>assert.deepEqual(R.parseRepoUrl(url),ref));
for(const url of ['https://github.com/settings/tokens','https://github.com/orgs/octo/repositories','https://github.com/search?q=demo','https://github.com/octo','https://evil.invalid/octo/demo','http://github.com/octo/demo','https://github.com/octo/x%2Fy','https://github.com:8443/octo/demo','https://evil@github.com/octo/demo'])test(`reject non-repository URL: ${url}`,()=>assert.equal(R.parseRepoUrl(url),null));
test('repository identity is case-insensitive',()=>assert.equal(R.repoKey({owner:'OcTo',repo:'Demo'}),'octo/demo'));
test('malformed references do not become request paths',()=>{for(const bad of [null,{}, {owner:'../x',repo:'demo'},{owner:'octo',repo:'..'},{owner:'octo',repo:'a/b'}])assert.throws(()=>R.validateRef(bad));});
test('compare and file URLs pin full SHAs and encode special path characters',()=>{assert.equal(R.compareUrl(ref,A,B),`https://github.com/octo/demo/compare/${A}...${B}`);assert.equal(R.fileUrl(ref,B,'a b/#c?.js'),`https://github.com/octo/demo/blob/${B}/a%20b/%23c%3F.js`);assert.throws(()=>R.fileUrl(ref,'main','file'));});
test('metadata normalization strips unrelated data',()=>assert.deepEqual(R.normalizeRepo({...apiRepo,secret:'x'}),meta));
test('commit normalization removes email and body',()=>{const value=R.normalizeCommits([apiCommit()])[0];assert.equal(value.message,'Change');assert.equal(value.author,'octo');assert.ok(!JSON.stringify(value).includes('secret@example'));});
test('comparison normalization strips source patches and untrusted URLs',()=>{const value=R.normalizeCompare(apiDiff());assert.equal(value.files[0].filename,'src/main.js');assert.ok(!JSON.stringify(value).includes('PRIVATE SOURCE'));assert.ok(!JSON.stringify(value).includes('evil.invalid'));});
test('300 returned files is conservatively labeled possibly incomplete',()=>{const d=apiDiff({files:Array.from({length:300},(_,i)=>({filename:`f${i}`,status:'added'}))});assert.equal(R.normalizeCompare(d).filesMayBeTruncated,true);d.files.pop();assert.equal(R.normalizeCompare(d).filesMayBeTruncated,false);});
for(const [name,baseline,repo,head,diff,state]of[
 ['first visit',null,meta,B,null,'untracked'],['empty',null,meta,null,null,'empty'],['same SHA',cp(),meta,A,null,'current'],['new repository ID',cp(),{...meta,id:50},B,null,'identity-changed'],['default branch changed',cp(),{...meta,defaultBranch:'next'},B,null,'branch-changed'],['linear progression',cp(),meta,B,{status:'ahead',behindBy:0,mergeBase:A},'ahead'],['diverged history',cp(),meta,B,{status:'diverged',behindBy:3,mergeBase:C},'history-changed'],['rewound history',cp(),meta,B,{status:'behind',behindBy:2,mergeBase:B},'history-changed'],['missing compare',cp(),meta,B,null,'comparison-unavailable'],['unexpected merge base',cp(),meta,B,{status:'ahead',behindBy:0,mergeBase:C},'history-changed']
])test(`classify: ${name}`,()=>assert.equal(R.classify(baseline,repo,head,diff),state));
test('file filters match renamed old paths and status',()=>{const files=[{filename:'new.js',previousFilename:'old.js',status:'renamed'},{filename:'other.js',status:'added'}];assert.equal(R.filterFiles(files,'OLD','renamed').length,1);assert.equal(R.filterFiles(files,'','removed').length,0);});
test('backup export is a whitelist without tokens or revision IDs',()=>{const text=R.serializeBackup([{...cp(),token:'SECRET_TOKEN',cache:'SECRET_CACHE'}]);assert.ok(!text.includes('SECRET'));assert.ok(!text.includes('revision'));assert.equal(R.parseBackup(text)[0].sha,A);});
test('backup import rejects malformed schema, SHA and excessive size',()=>{for(const text of ['[]','not json',JSON.stringify({app:'RepoDelta',schemaVersion:2,checkpoints:[]}),JSON.stringify({app:'RepoDelta',schemaVersion:1,checkpoints:[cp({sha:'main'})]}),' '.repeat(1048577)])assert.throws(()=>R.parseBackup(text),{code:'INVALID_BACKUP'});});
test('backup parser ignores unexpected fields and validates every entry',()=>{const text=JSON.stringify({app:'RepoDelta',schemaVersion:1,token:'x',checkpoints:[{...cp(),token:'x'}]});assert.deepEqual(Object.keys(R.parseBackup(text)[0]).sort(),['branch','markedAt','ref','repoId','sha']);});
test('settings only accept supported language and booleans',()=>{assert.deepEqual(R.cleanSettings({language:'fr',autoCheck:'false'}),{language:'en',autoCheck:true});assert.deepEqual(R.cleanSettings({language:'ko',autoCheck:false}),{language:'ko',autoCheck:false});});
test('EN/KR string and error dictionaries have identical keys',()=>{assert.deepEqual(Object.keys(R.STRINGS.en).sort(),Object.keys(R.STRINGS.ko).sort());assert.deepEqual(Object.keys(R.ERRORS.en).sort(),Object.keys(R.ERRORS.ko).sort());});
test('translated placeholder sets match',()=>{for(const k of Object.keys(R.STRINGS.en)){const en=(R.STRINGS.en[k].match(/\{\w+\}/g)||[]).sort();const ko=(R.STRINGS.ko[k].match(/\{\w+\}/g)||[]).sort();assert.deepEqual(en,ko,k);}});
test('public errors do not leak arbitrary exception messages',()=>assert.deepEqual(R.publicError(new Error('SECRET_TOKEN')),{code:'INTERNAL',status:0,retryAt:0,detail:''}));
