import test from 'node:test';
import assert from 'node:assert/strict';
import {R,A,B,C,ref,meta,cp,setup} from './helpers.mjs';
test('local and session stores restrict access to trusted contexts',async()=>{const{st}=await setup();assert.equal(st.local.accessLevel,'TRUSTED_CONTEXTS');assert.equal(st.session.accessLevel,'TRUSTED_CONTEXTS');});
test('BOOT on untracked repository makes zero API requests',async()=>{const{service,calls}=await setup();assert.equal((await service.boot(ref)).checkpoint,null);assert.equal(calls.length,0);});
test('opening or checking does not create a checkpoint',async()=>{const{service,store}=await setup();const s=await service.check(ref);assert.equal(s.state,'untracked');assert.equal(await store.checkpoint(ref),null);assert.ok(!Object.hasOwn(s,'epoch'));});
test('initial mark stores exactly the displayed revision with no fresh HEAD call',async()=>{const{service,store,calls}=await setup();const s=await service.check(ref);const n=calls.length;const next=await service.mark(ref,s.id);assert.equal((await store.checkpoint(ref)).sha,B);assert.equal(calls.length,n);assert.equal(next.state,'current');});
test('checking an ahead repository preserves its old baseline',async()=>{const base=cp();const{service,store}=await setup({baseline:base});const s=await service.check(ref);assert.equal(s.state,'ahead');assert.equal((await store.checkpoint(ref)).sha,A);});
test('mark pins viewed HEAD even if upstream advances during review',async()=>{const{service,api,store}=await setup({baseline:cp()});const s=await service.check(ref);const old=api.get.bind(api);api.get=async(p,k,f)=>k==='head'?{data:[{sha:C}],at:Date.now(),cached:false}:old(p,k,f);await service.mark(ref,s.id);assert.equal((await store.checkpoint(ref)).sha,B);});
test('older tab cannot overwrite a newer checkpoint',async()=>{const{service}=await setup({baseline:cp()});const s1=await service.check(ref),s2=await service.check(ref);await service.mark(ref,s1.id);await assert.rejects(service.mark(ref,s2.id),{code:'STALE_CHECKPOINT'});});
test('concurrent marks produce one winner, one stale error',async()=>{const{service}=await setup({baseline:cp()});const a=await service.check(ref),b=await service.check(ref);const results=await Promise.allSettled([service.mark(ref,a.id),service.mark(ref,b.id)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'STALE_CHECKPOINT');});
test('another checkpoint saved during network request invalidates the check',async()=>{const{service,store,api}=await setup({baseline:cp()});const old=api.get.bind(api);api.get=async(p,k,f)=>{const x=await old(p,k,f);if(k==='head')await store.mutateCheckpoints(r=>{r[R.repoKey(ref)]=cp({sha:C});});return x;};await assert.rejects(service.check(ref),{code:'STALE_CHECKPOINT'});});
test('empty repository cannot be marked',async()=>{const{service}=await setup({head:null});const s=await service.check(ref);assert.equal(s.state,'empty');await assert.rejects(service.mark(ref,s.id),{code:'EMPTY_REPO'});});
for(const[name,options,state]of[
 ['branch switch',{repository:{...meta,defaultBranch:'release/next'}},'branch-changed'],
 ['repository replacement',{repository:{...meta,id:999}},'identity-changed'],
 ['rewritten history',{comparison:{status:'diverged',aheadBy:1,behindBy:2,totalCommits:1,mergeBase:C,commits:[],files:[],filesMayBeTruncated:false}},'history-changed'],
 ['unavailable comparison',{compareError:new R.DeltaError('NOT_FOUND',404)},'comparison-unavailable']
])test(`${name} requires explicit reset confirmation`,async()=>{const{service,store}=await setup({baseline:cp(),...options});const s=await service.check(ref);assert.equal(s.state,state);await assert.rejects(service.mark(ref,s.id),{code:'RESET_CONFIRM_REQUIRED'});assert.equal((await store.checkpoint(ref)).sha,A);await service.mark(ref,s.id,true);assert.equal((await store.checkpoint(ref)).sha,B);});
test('rate limit is not mislabeled as rewritten history',async()=>{const{service}=await setup({baseline:cp(),compareError:new R.DeltaError('RATE_LIMIT',429)});await assert.rejects(service.check(ref),{code:'RATE_LIMIT'});});
test('default branch with slash is query-encoded',async()=>{const{service,calls}=await setup({repository:{...meta,defaultBranch:'release/next'}});await service.check(ref);assert.ok(calls.some(c=>c.path.includes('sha=release%2Fnext')));});
test('more pages retain the first-page file list and pinned comparison',async()=>{
 const commits=Array.from({length:100},(_,i)=>({sha:i.toString(16).padStart(40,'0'),message:`c${i}`}));
 const diff={status:'ahead',aheadBy:102,behindBy:0,totalCommits:102,mergeBase:A,commits,files:[{filename:'retained.js',status:'added',additions:1,deletions:0}],filesMayBeTruncated:false};
 const{service,api,calls}=await setup({baseline:cp(),comparison:diff});const s=await service.check(ref);const old=api.get.bind(api);
 api.get=async(p,k,f)=>p.endsWith('page=2')?{data:{...diff,files:[],commits:[{sha:C},{sha:B}]},at:Date.now(),cached:false}:old(p,k,f);
 const next=await service.loadMore(ref,s.id);assert.equal(next.diff.commits.length,102);assert.equal(next.diff.files[0].filename,'retained.js');assert.equal(next.headSha,B);
 await assert.rejects(service.loadMore(ref,s.id),{code:'NO_MORE_PAGES'});
});
test('loading stops at 500 commits',async()=>{const diff={status:'ahead',aheadBy:501,behindBy:0,totalCommits:501,mergeBase:A,commits:Array.from({length:500},(_,i)=>({sha:i.toString(16).padStart(40,'0')})),files:[],filesMayBeTruncated:false};const{service}=await setup({baseline:cp(),comparison:diff});const s=await service.check(ref);await assert.rejects(service.loadMore(ref,s.id),{code:'NO_MORE_PAGES'});});
test('cross-repository snapshot replay is denied',async()=>{const{service}=await setup();const s=await service.check(ref);await assert.rejects(service.mark({owner:'other',repo:'repo'},s.id),{code:'FORBIDDEN'});});
test('snapshot expires after 30 minutes',async()=>{let clock=1000;const{service}=await setup({now:()=>clock});const s=await service.check(ref);clock+=R.LIMITS.snapshotMs+1;await assert.rejects(service.mark(ref,s.id),{code:'SNAPSHOT_EXPIRED'});});
test('tokens exist only in session and never in backup or options response',async()=>{const{service,st}=await setup({baseline:cp()});await service.setToken('github_pat_'+ 'x'.repeat(30));assert.ok(!JSON.stringify(await st.local.get(null)).includes('github_pat_'));assert.ok(JSON.stringify(await st.session.get(null)).includes('github_pat_'));assert.ok(!JSON.stringify(await service.options()).includes('github_pat_'));});
test('changing authentication invalidates old snapshots and preserves checkpoints',async()=>{const{service,store}=await setup({baseline:cp()});const s=await service.check(ref);await service.setToken('github_pat_'+ 'x'.repeat(30));await assert.rejects(service.mark(ref,s.id),{code:'SNAPSHOT_EXPIRED'});assert.equal((await store.checkpoint(ref)).sha,A);});
test('backup merge skips existing and duplicate entries',async()=>{const{service,store}=await setup({baseline:cp()});const extra=cp({ref:{owner:'new',repo:'repo'},sha:C});const result=await service.importBackup(R.serializeBackup([cp({sha:B}),extra,extra]));assert.deepEqual(result,{added:1,skipped:2});assert.equal((await store.checkpoint(ref)).sha,A);});
test('malformed backup is atomic and leaves data unchanged',async()=>{const{service,store}=await setup({baseline:cp()});const before=await store.checkpoints();await assert.rejects(service.importBackup(JSON.stringify({app:'RepoDelta',schemaVersion:1,checkpoints:[cp(),{oops:true}]})),{code:'INVALID_BACKUP'});assert.deepEqual(await store.checkpoints(),before);});
test('checkpoint limit rejects a whole import without partial writes',async()=>{const{service,store}=await setup({baseline:cp()});const entries=Array.from({length:1000},(_,i)=>cp({ref:{owner:'new',repo:`r${i}`}}));await assert.rejects(service.importBackup(R.serializeBackup(entries)),{code:'TRACKING_LIMIT'});assert.equal(Object.keys(await store.checkpoints()).length,1);});
test('untrack requires matching revision and never writes GitHub',async()=>{const base=cp();const{service,store,calls}=await setup({baseline:base});await assert.rejects(service.untrack(ref,'wrong'),{code:'STALE_CHECKPOINT'});await service.untrack(ref,base.revision);assert.equal(await store.checkpoint(ref),null);assert.equal(calls.length,0);});
test('serialized local writes preserve concurrent unrelated repositories',async()=>{const{store}=await setup();await Promise.all(Array.from({length:40},(_,i)=>store.mutateCheckpoints(r=>{r[`org/r${i}`]=cp({ref:{owner:'org',repo:`r${i}`}});})));assert.equal(Object.keys(await store.checkpoints()).length,40);});
const contentSender={id:'extension-id',url:'https://github.com/octo/demo',tab:{id:1},frameId:0};
test('content scripts cannot read options, tokens, or export all checkpoints',()=>{for(const type of ['OPTIONS','SET_TOKEN','EXPORT','IMPORT','CLEAR_CHECKPOINTS'])assert.throws(()=>R.authorizeMessage({namespace:'RepoDelta',type,ref},contentSender,'extension-id'),{code:'FORBIDDEN'});});
test('content scripts are scoped to their sender repository',()=>assert.throws(()=>R.authorizeMessage({namespace:'RepoDelta',type:'CHECK',ref:{owner:'other',repo:'private'}},contentSender,'extension-id'),{code:'FORBIDDEN'}));
test('messages from another extension or subframes are denied',()=>{assert.throws(()=>R.authorizeMessage({namespace:'RepoDelta',type:'CHECK',ref},{...contentSender,id:'other'},'extension-id'));assert.throws(()=>R.authorizeMessage({namespace:'RepoDelta',type:'CHECK',ref},{...contentSender,frameId:2},'extension-id'));});
test('owned settings page can export',()=>assert.equal(R.authorizeMessage({namespace:'RepoDelta',type:'EXPORT'},{id:'extension-id',url:'chrome-extension://extension-id/options.html'},'extension-id'),true));
